/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 cypherThree.gltf 
*/

import React, { useEffect } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/cypherThree.gltf')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    if (actions) {
      // Play the first animation found
      const action = actions[Object.keys(actions)[0]];
      action.play();
    }
  }, [actions]);
  return (
    <group ref={group} {...props} dispose={null} position={[-1.4, 0, 0]} rotation={[0, Math.PI /11, 0]}>
      <group name="Scene">
        <group name="Cypher_CS_Gumshoe_S0_Skelmeshmd" rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="Cypher_Body" geometry={nodes.Cypher_Body.geometry} material={materials['Material.001']} skeleton={nodes.Cypher_Body.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/cypherThree.gltf')
